### ISSUE TITLE
Backend File Creation

### ISSUE THREAD

**Issue by mnchase** [sidharthanup/Audio-Analyzer-and-Transcription-Tool#32]
Do we want a saved document?  Allow for user to see preview of transcript and then save if desired?

**Comment by rphill299** [comment]
I vote for a checkbox "Save Outputs"

- If checked, final outputs are saved automatically as .txts.
- If unchecked, the user has the option to save individual tabs of output.
- User has option to choose the output folder; default is {proj}/outputs.
- User can be warned of existing outputs, and asked if they want to transcribe again.

Also, isn't this the same as https://github.com/sidharthanup/Audio-Analyzer-and-Transcription-Tool/issues/24 ?

**Comment by rphill299** [comment]
See #35 and open new issue if anything needs changed
