### ISSUE TITLE
Sequential processing

### ISSUE THREAD

**Issue by mnchase** [sidharthanup/Audio-Analyzer-and-Transcription-Tool#43]
For large folders of files, users may prefer slower overall output if they receive files to work with more quickly.

- [x] #48
- [x] #49
- [ ] Integrate with saving outputs
- [ ] Integrate with Diarization #30 
- [ ] Integrate with Translation #39

**Comment by rphill299** [comment]
The code is in a good spot for this to be implemented.

A big roadblock is having react wait for each axios call to finish.  currently each file gets sent to the backend at the same time and it isn't handled properly.

I've mostly looked into using await/async, with no success.  I've followed code snippets from online exactly, but I've never gotten anything to actually wait (backend always receives all calls at once)

**Comment by rphill299** [comment]
Completed the implementation of sequential processing within a new endpoint.

React waits for each axios call to finish by recursively making the next axios call within the .finally() block.

Sequential call can easily be configured to pass user's file to different endpoints, and expects to receive back a status code (0 for success), a transcript, and optionally a detected language
